spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: c907b554642940
    password: c21441b2a63358
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            enable: false
  messages:
    basename: messages
  mvc:
    throw-exception-if-no-handler-found: true